### ISSUE TITLE
inconsistent synapse export

### ISSUE THREAD

**Issue by bsumirak** [NeuroBox3D/NeuGen#31]
Synapses are not exported consistently with the various export methods:

For a default project (new project Neocortex, defaults for all parameters)

- HOC exports more alpha synapses than NGX and TXT,
- the location of synapses exported as TXT, NGX and HOC are all different:
   - TXT: all synapses seem to be located at an end of a section,
   - NGX: all synapses seem to be located in a vertex,
   - HOC: synapses are located anywhere.

**Comment by stephanmg** [comment]
Thanks for reporting this. Are you using the master or devel branch? NGX is not really supported and should only be available in the (experimental) devel branch and will be dropped most likely.

HOC and TXT export should in fact produce the same output as you pointed out. Is the positioning of the synapses as expected for the HOC export? Since this was the original implementation of SW one should check this implementation as TXT and NGX export were both derived based on this implementation (Only Neocortex is supported though). See also open issue #13.

**Comment by stephanmg** [comment]
Without additional details on the nature of the issue and which branch is used, I am going to close this issue. Feel free to reopen this issue.
